apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: 1-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  zzz_deprecatedclustername: ""
  managedfields: []
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: repofortestingm2k
      name: repofortestingm2k
    spec:
      ports:
        - name: port-8080
          port: 8080
          targetPort: 8080
      selector:
        move2kube.konveyor.io/service: repofortestingm2k
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: "1"
      name: "1"
    spec:
      rules:
        - host: 1.com
          http:
            paths:
              - backend:
                  service:
                    name: repofortestingm2k
                    port:
                      name: port-8080
                path: /repofortestingm2k
                pathType: Prefix
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: repofortestingm2k
      name: repofortestingm2k
    spec:
      replicas: ${{COMMON_REPLICAS}}
      selector:
        matchLabels:
          move2kube.konveyor.io/service: repofortestingm2k
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            move2kube.konveyor.io/service: repofortestingm2k
          name: repofortestingm2k
        spec:
          containers:
            - image: quay.io/1/repofortestingm2k:latest
              imagePullPolicy: Always
              name: repofortestingm2k
              ports:
                - containerPort: 8080
              resources: {}
          restartPolicy: Always
          securityContext: {}
    status: {}
parameters:
  - name: COMMON_REPLICAS
    value: "2"
